#ifndef HEADER_RAY_CONFIG
#define HEADER_RAY_CONFIG

#define TRACE_DEPTH 9000
#define AMBIENT_COLOUR (colour(32, 32, 32))
#define SPECULAR_POWER 20
#define LIGHT_FALLOFF 500
#define COL_MAX 300
#define SCREEN_RESOLUTION_WIDTH 1920
#define SCREEN_RESOLUTION_HEIGHT 1080
#define SCREEN_DISTANCE 5
#define SCREEN_SIZE 2.0
#define EYE_POSITION (vector3(0, 0, 0)) 
#define EYE_DIRECTION (vector3(0, 0, 1)) 
#define SUPER_SAMPLE 4
#define BACKGROUND_COLOUR (colour(150, 150, 150))
#define SHADOWS_ENABLE
#define REFLECTION_ENABLE

#endif
